Authorization:
  description: Token authentication header.
  type: string
  example: |
    Authorization: Token token=QWxhZGRpbjpvcGVuIHNlc2FtZQ==
Accept:
  description: Media type of the **response** body.
  type: string
  example: |
    Accept: application/vnd.teamorga.v1+json
